

async function main () {

}

main().catch((error) => {
  console.log(error)
  process.exit(1)
})